In [1]:
import pandas as pd

df_gastos_ventas = pd.read_excel('../data/GASTOS-MANDRIL.xlsm', sheet_name='VENTAS', header=1)
df_gastos_lista = pd.read_excel('../data/GASTOS-MANDRIL.xlsm', sheet_name='LISTA', index_col='Código')

df_gastos_ventas['RUC/DNI'].unique()

array([nan, '20559548287', '41113035', ..., '42314397', '20601888875',
       '20516859548'], shape=(3012,), dtype=object)

In [2]:
df_gastos_ventas.columns

Index(['Código', 'Producto', 'Precio Venta', 'Cant.', 'Total Venta', 'Fecha',
       'Medio', 'Comprobante', 'Nombre', 'RUC/DNI', 'Número', 'Observación',
       'Precio Compra', 'Suma compras', 'Ganancia', 'Garantia',
       'Tipo Documento', 'Nombre Contacto', 'Número Documento Contacto',
       'Observación2'],
      dtype='object')

In [3]:
df_gastos_ventas['Código'].unique().shape

(348,)

# CORRECCIONES

## Duplicados

1. Duplicate exact rows

In [13]:
filter_duplicates = df_gastos_ventas.duplicated(keep=False)
df_gastos_ventas.iloc[df_gastos_ventas[filter_duplicates].index, 0:12]

,Código,Producto,Precio Venta,Cant.,Total Venta,Fecha,Medio,Comprobante,Nombre,RUC/DNI,Número,Observación
3587,MI206,Termometro Horno 400° Perno Largo,80.0,1,80.0,2023-08-18,Falabella.com,S/D,FABIOLA ABIGAIL LUME,46451551,NaN,NaN
3588,MI206,Termometro Horno 400° Perno Largo,80.0,1,80.0,2023-08-18,Falabella.com,S/D,FABIOLA ABIGAIL LUME,46451551,NaN,NaN
4063,MI205,Cable Aviator M12 4pin 3M,25.0,3,75.0,2023-06-02,WhatsApp,Factura,WSNTRANSCOM LOGISTICA S.A.C.,20603083246,958 602 541,E001-1842
4072,MI205,Cable Aviator M12 4pin 3M,25.0,3,75.0,2023-06-02,WhatsApp,Factura,WSNTRANSCOM LOGISTICA S.A.C.,20603083246,958 602 541,E001-1842
4814,MI074,Cable Usb 8 Pines Camaras,25.0,1,25.0,2022-12-15,Mercado Libre,S/D,Carlos Begazo,NaN,NaN,NaN
4815,MI074,Cable Usb 8 Pines Camaras,25.0,1,25.0,2022-12-15,Mercado Libre,S/D,Carlos Begazo,NaN,NaN,NaN
4958,MI233,Antena WIFI 7dbi RP-SMA,35.0,1,35.0,2022-11-16,Linio,S/D,Abdías Racho Sánchez,46861831,NaN,NaN
4959,MI233,Antena WIFI 7dbi RP-SMA,35.0,1,35.0,2022-11-16,Linio,S/D,Abdías Racho Sánchez,46861831,NaN,NaN
5315,MI060,Cable Audio RCA Jack 3.5mm hembra,15.0,1,15.0,2022-09-23,Mercado Libre,S/D,Alejandro Sanchez,NaN,NaN,NaN
5316,MI060,Cable Audio RCA Jack 3.5mm hembra,15.0,1,15.0,2022-09-23,Mercado Libre,S/D,Alejandro Sanchez,NaN,NaN,NaN
7193,MI137,Mdvr Grabador 512GB DVR 4 canales,500.0,7,3500.0,2022-01-10,WhatsApp,Factura,ELIAS MINA MAURO EDWIN,10297128596,959 973 247,E001-1034
7194,MI137,Mdvr Grabador 512GB DVR 4 canales,500.0,7,3500.0,2022-01-10,WhatsApp,Factura,ELIAS MINA MAURO EDWIN,10297128596,959 973 247,E001-1034
7209,MI206,Termometro Horno 400° Perno Largo,80.0,1,80.0,2022-01-08,Mercado Libre,S/D,Percy Huallpa Rodriguez,NaN,NaN,NaN
7210,MI206,Termometro Horno 400° Perno Largo,80.0,1,80.0,2022-01-08,Mercado Libre,S/D,Percy Huallpa Rodriguez,NaN,NaN,NaN
7369,MI128,Destornillador Tri-Wing Cross (2 Unidades),15.0,1,15.0,2021-12-16,Tienda,S/D,NaN,NaN,NaN,NaN
7370,MI128,Destornillador Tri-Wing Cross (2 Unidades),15.0,1,15.0,2021-12-16,Tienda,S/D,NaN,NaN,NaN,NaN
8598,MI192,Destornillador Pentalobe 0.8mm-1.2mm (2 Unidades),15.0,1,15.0,2021-06-11,Tienda,S/D,NaN,NaN,NaN,NaN
8599,MI192,Destornillador Pentalobe 0.8mm-1.2mm (2 Unidades),15.0,1,15.0,2021-06-11,Tienda,S/D,NaN,NaN,NaN,NaN
9132,MI003,Adaptador Aviation M12 4 pines / AV - M12,20.0,1,20.0,2021-03-15,WhatsApp,S/D,Soluciones Dican SAC.,NaN,985 907 443,NaN
9134,MI003,Adaptador Aviation M12 4 pines / AV - M12,20.0,1,20.0,2021-03-15,WhatsApp,S/D,Soluciones Dican SAC.,NaN,985 907 443,NaN

2. Products with same code but differente name

In [5]:
df = df_gastos_ventas.drop_duplicates(subset=['Código', 'Producto']).sort_values(by='Código', ascending=True)
filter_duplicates = df.duplicated(subset=['Código'], keep=False)
df.loc[filter_duplicates, ['Código', 'Producto']]

     Código                                    Producto
231   MI344      Bateria Renata 394 (Pack x 2 unidades)
3269  MI344                          Bateria Renata 394
13    MI357  CAMARA AHD INTERIOR 1080P -DOMO METAL NTSC
2313  MI357   CAMARA AHD INTERIOR 720P -DOMO METAL NTSC

3. Companies with same RUC but differente name

In [14]:
# pd.set_option('display.max_rows', None)
pd.reset_option('display.max_rows', None)
df_gastos_ventas['Nombre'] = df_gastos_ventas['Nombre'].str.strip()
df = df_gastos_ventas.drop_duplicates(subset=['RUC/DNI', 'Nombre']).sort_values(by='Código', ascending=True)
filter_duplicates = df.duplicated(subset=['RUC/DNI'], keep=False)
df_unique_dni_ruc = df.loc[filter_duplicates, ['RUC/DNI', 'Nombre']].dropna(subset=['RUC/DNI']).astype({'RUC/DNI': 'string'}).sort_values(by='RUC/DNI')
df_unique_dni_ruc

          RUC/DNI                         Nombre
6915  10434089005  CARRILLO DURAND VICTOR MARTIN
6935  10434089005                Martin Carrillo
5289  20508416262          GRUPO INDECOEL S.R.L.
8354  20508416262      ANGIE PLASTIC Y SERVICIOS
3823     41728403    Willman Cuyutupac Sotomayor
8859     41728403    WILLMAN CUYUTUPAC SOTOMAYOR

4. Invoice code with different company identifier

5. Invoice code with different company identifier

In [7]:
filter = df_gastos_ventas['Observación'].str.startswith('E') & df_gastos_ventas.duplicated(subset=['Observación', 'RUC/DNI'], keep=False)
df = df_gastos_ventas.loc[filter, ['RUC/DNI', 'Observación']].drop_duplicates(subset=['RUC/DNI', 'Observación'])
df[df.duplicated()]

Empty DataFrame
Columns: [RUC/DNI, Observación]
Index: []

6. Get the invoices code and the missing ones

In [8]:
regex_invoice_code = r'E\d{3}-\d{1,4}'
invoices_set = { f'E001-{num}' for num in range(491, 2994) }

filt = df_gastos_ventas['Observación'].str.contains(regex_invoice_code, na=False)
df_unique_invoice_code = df_gastos_ventas.loc[filt, ['Observación']].drop_duplicates()
list_unique_invoice_code_from_gastos = set(df_unique_invoice_code['Observación'].to_list())

difference = list(invoices_set - list_unique_invoice_code_from_gastos)

pd.Series(difference).to_csv('../output/invoices_not_in_gastos.csv', encoding='utf-8')

In [16]:
regex_invoice_code = r'E\d{3}-(\d{1,4})'

df_invoices = df_gastos_ventas['Observación'].str.extract(regex_invoice_code).dropna().astype(int)
df_invoices.sort_values(by=0, ascending=True, inplace=True)
df_invoices

         0
5223   154
9619   491
9613   492
9615   492
9614   492
...    ...
14    3003
15    3003
16    3003
13    3003
1     3004

[4587 rows x 1 columns]

7. Sale with invoice code but without company identifier or company name

In [10]:
filter_missing_invoices_name = ~df_gastos_ventas['Observación'].isna() & df_gastos_ventas['RUC/DNI'].isna()
regex_boleta = r'EB\d{2}-\d{1,4}'
regex_factura = r'E\d{3}-\d{1,4}'

df = df_gastos_ventas.loc[filter_missing_invoices_name, ['Observación']].rename(columns={'Observación': 'num_comprobante'})
df['num_comprobante'] = df['num_comprobante'].str.replace(" ", "").drop_duplicates().sort_values()

df_boleta = df[df['num_comprobante'].str.contains(regex_boleta, na=False)]
df_factura = df[df['num_comprobante'].str.contains(regex_factura, na=False)]

df_boleta['num_comprobante'].to_csv('../output/invoices_with_missing_company_code_boleta.csv', encoding='utf-8', index=False)
df_factura['num_comprobante'].to_csv('../output/invoices_with_missing_company_code_factura.csv', encoding='utf-8', index=False)

8. Invoices with invalid codes (EXXX-XXXX, EBXX-XXXX)

In [11]:
regex = r'(EB\d{2}|E\d{3})-\d{1,4}$'

filt = df_gastos_ventas['Observación'].str.match(regex, na=False)
df_gastos_ventas.loc[~filt, 'Observación'].drop_duplicates()

0                                 NaN
2                     pagó 150 soles
109                        EB01-1268
318               E001-2929/E001-2930
405               E001-2897/E001-2903
415     E001-2900/E001-2901/E001-2902
1297              E001-2636/E001-2644
1380    E001-2598/E001-2599/E001-2600
3068              E001-2087/E001-2088
4740                 E001-1669 / 1670
5480            E001-1463 / E001-1464
Name: Observación, dtype: object

# Export to CSV

1. Apply strip to columns

In [12]:
df = df_gastos_ventas.iloc[:, 0:12]
df['Nombre'] = "'" + df['Nombre'].astype('string').str.strip()
df['RUC/DNI'] = "'" + df['RUC/DNI'].astype('string').str.strip()
df['Número'] = "'" + df['Número'].astype('string').str.strip()
df['Observación'] = "'" + df['Observación'].astype('string').str.strip()
df.to_csv('../output/gastos_ventas_cleaned.csv', index=False, encoding='utf-8-sig')

df.head(15)

,Código,Producto,Precio Venta,Cant.,Total Venta,Fecha,Medio,Comprobante,Nombre,RUC/DNI,Número,Observación
0,MI255,Micrometro Digital,60.0,1,60.0,2025-08-25,WhatsApp,S/D,<NA>,<NA>,'946 564 561,<NA>
1,MI277,Sensor de Fatiga,550.0,1,550.0,2025-08-25,WhatsApp,Factura,'TRANSPORTES Y CONSTRUCCIONES JOILSAC S.A.C. -...,'20559548287,'944 217 377,'E001-3004
2,MI035,Adaptador SMA Macho a RPSMA Hembra 90°,15.0,5,75.0,2025-08-25,WhatsApp,S/D,'César Quezada,<NA>,'946 268 130,'pagó 150 soles
3,MI140,Medidor de cocadas Llantas,45.0,1,45.0,2025-08-25,Falabella.com,S/D,'Janeth noriega,'41113035,<NA>,<NA>
4,MI079,Calibrador Digital Vernier Pie de rey,50.0,1,50.0,2025-08-24,Falabella.com,S/D,'liliana vargas,'29721262,<NA>,<NA>
5,MI394,Balanza De Mano Digital 50kg Bascula Maleta Tr...,35.0,1,35.0,2025-08-24,Mercado Libre,S/D,'Raisa Villaverde,<NA>,<NA>,<NA>
6,MI263,"Mini bomba de Motor sumergible DC 3-5V, 70-120L/H",15.0,1,15.0,2025-08-24,Falabella.com,S/D,'Iván ames Ames Lizarbe,<NA>,<NA>,<NA>
7,MI263,"Mini bomba de Motor sumergible DC 3-5V, 70-120L/H",15.0,1,15.0,2025-08-24,Falabella.com,S/D,'roger jimenez garcia,<NA>,<NA>,<NA>
8,MI073,Cable POE Mellizo,25.0,1,25.0,2025-08-24,Falabella.com,S/D,'Gonzalo manuel ochoa quesada,<NA>,<NA>,<NA>
9,MI158,"Pantalla Auto 5"" Plegable",170.0,1,170.0,2025-08-23,Falabella.com,S/D,'GROVER DAVID ESPINOZA SOLIS,<NA>,<NA>,<NA>
10,MI277,Sensor de Fatiga,550.0,1,550.0,2025-08-23,WhatsApp,Factura,'EMPRESA CARHUAMAYO S.A.C.,'20551261353,'989 081 459,'E001-3003
11,MI265,Mdvr Grabador 4G / GPS 512GB,1200.0,1,1200.0,2025-08-23,WhatsApp,Factura,'EMPRESA CARHUAMAYO S.A.C.,'20551261353,'989 081 459,'E001-3003
12,MI385,Memoria Micro SD Kingston 512GB GOPLUS CANVAS ...,250.0,1,250.0,2025-08-23,WhatsApp,Factura,'EMPRESA CARHUAMAYO S.A.C.,'20551261353,'989 081 459,'E001-3003
13,MI357,CAMARA AHD INTERIOR 1080P -DOMO METAL NTSC,170.0,1,170.0,2025-08-23,WhatsApp,Factura,'EMPRESA CARHUAMAYO S.A.C.,'20551261353,'989 081 459,'E001-3003
14,MI306,CAMARA AHD EXTERIOR 1080P - LATERAL ESPEJO NTSC,170.0,2,340.0,2025-08-23,WhatsApp,Factura,'EMPRESA CARHUAMAYO S.A.C.,'20551261353,'989 081 459,'E001-3003